BASE = 2320000

LOCATION_MAPPING = {
	--Arbiter's Grounds Locations
	[BASE + 0] = {"@Arbiter's Grounds/1F/Big Key Chest"},
	[BASE + 1] = {"@Arbiter's Grounds/B2/Death Sword Chest"},
	[BASE + 2] = {"@Arbiter's Grounds/4F/Dungeon Reward"},
	[BASE + 3] = {"@Arbiter's Grounds/B1/East Lower Turnable Redead Chest"},
	[BASE + 4] = {"@Arbiter's Grounds/Poes1F/East Turning Room Poe"},
	[BASE + 5] = {"@Arbiter's Grounds/2F/East Upper Turnable Chest"},
	[BASE + 6] = {"@Arbiter's Grounds/2F/East Upper Turnable Redead Chest"},
	[BASE + 7] = {"@Arbiter's Grounds/1F/Entrance Chest"},
	[BASE + 8] = {"@Arbiter's Grounds/2F/Ghoul Rat Room Chest"},
	[BASE + 9] = {"@Arbiter's Grounds/Poes2F/Hidden Wall Poe"},
	[BASE + 10] = {"@Arbiter's Grounds/B1/North Turning Room Chest"},
	[BASE + 11] = {"@Arbiter's Grounds/B2/Spinner Room First Small Chest"},
	[BASE + 12] = {"@Arbiter's Grounds/B2/Spinner Room Lower Central Small Chest"},
	[BASE + 13] = {"@Arbiter's Grounds/B1/Spinner Room Lower North Chest"},
	[BASE + 14] = {"@Arbiter's Grounds/B2/Spinner Room Second Small Chest"},
	[BASE + 15] = {"@Arbiter's Grounds/B2/Spinner Room Stalfos Alcove Chest"},
	[BASE + 16] = {"@Arbiter's Grounds/4F/Stallord Heart Container"},
	[BASE + 17] = {"@Arbiter's Grounds/1F/Torch Room East Chest"},
	[BASE + 18] = {"@Arbiter's Grounds/Poes1F/Torch Room Poe"},
	[BASE + 19] = {"@Arbiter's Grounds/1F/Torch Room West Chest"},
	[BASE + 20] = {"@Arbiter's Grounds/1F/West Chandelier Chest"},
	[BASE + 21] = {"@Arbiter's Grounds/Poes2F/West Poe"},
	[BASE + 22] = {"@Arbiter's Grounds/1F/West Small Chest Behind Block"},
	[BASE + 23] = {"@Arbiter's Grounds/1F/West Stalfos Northeast Chest"},
	[BASE + 24] = {"@Arbiter's Grounds/1F/West Stalfos West Chest"},
	
	--City in The Sky Locations
	[BASE + 25] = {"@City in the Sky/B3/Aeralfos Chest"},
	[BASE + 26] = {"@City in the Sky/5F/Argorok Heart Container"},
	[BASE + 27] = {"@City in the Sky/2F/Baba Tower Alcove Chest"},
	[BASE + 28] = {"@City in the Sky/2F/Baba Tower Narrow Ledge Chest"},
	[BASE + 29] = {"@City in the Sky/3F/Baba Tower Top Small Chest"},
	[BASE + 30] = {"@City in the Sky/4F/Big Key Chest"},
	[BASE + 31] = {"@City in the Sky/4F/Central Outside Ledge Chest"},
	[BASE + 32] = {"@City in the Sky/4F/Central Outside Poe Island Chest"},
	[BASE + 33] = {"@City in the Sky/1F/Chest Behind North Fan"},
	[BASE + 34] = {"@City in the Sky/3F/Chest Below Big Key Chest"},
	[BASE + 35] = {"@City in the Sky/5F/Dungeon Reward"},
	[BASE + 36] = {"@City in the Sky/1F/East First Wing Chest After Fans"},
	[BASE + 37] = {"@City in the Sky/1F/East Tile Worm Small Chest"},
	[BASE + 38] = {"@City in the Sky/2F/East Wing After Dinalfos Alcove Chest"},
	[BASE + 39] = {"@City in the Sky/2F/East Wing After Dinalfos Ledge Chest"},
	[BASE + 40] = {"@City in the Sky/B1/East Wing Lower Level Chest"},
	[BASE + 41] = {"@City in the Sky/Poes2F/Garden Island Poe"},
	[BASE + 42] = {"@City in the Sky/Poes4F/Poe Above Central Fan"},
	[BASE + 43] = {"@City in the Sky/1F/Underwater East Chest"},
	[BASE + 44] = {"@City in the Sky/1F/Underwater West Chest"},
	[BASE + 45] = {"@City in the Sky/3F/West Garden Corner Chest"},
	[BASE + 46] = {"@City in the Sky/3F/West Garden Ledge Chest"},
	[BASE + 47] = {"@City in the Sky/2F/West Garden Lone Island Chest"},
	[BASE + 48] = {"@City in the Sky/2F/West Garden Lower Chest"},
	[BASE + 49] = {"@City in the Sky/B1/West Wing Baba Balcony Chest"},
	[BASE + 50] = {"@City in the Sky/1F/West Wing First Chest"},
	[BASE + 51] = {"@City in the Sky/1F/West Wing Narrow Ledge Chest"},
	[BASE + 52] = {"@City in the Sky/1F/West Wing Tile Worm Chest"},
	
	--Forest Temple Locations
	[BASE + 53] = {"@Forest Temple/1F/Big Baba Key"},
	[BASE + 54] = {"@Forest Temple/1F/Big Key Chest"},
	[BASE + 55] = {"@Forest Temple/1F/Central Chest Behind Stairs"},
	[BASE + 56] = {"@Forest Temple/1F/Central Chest Hanging From Web"},
	[BASE + 57] = {"@Forest Temple/1F/Central North Chest"},
	[BASE + 58] = {"@Forest Temple/1F/Diababa Heart Container"},
	[BASE + 59] = {"@Forest Temple/1F/Dungeon Reward"},
	[BASE + 60] = {"@Forest Temple/1F/East Tile Worm Chest"},
	[BASE + 61] = {"@Forest Temple/1F/East Water Cave Chest"},
	[BASE + 62] = {"@Forest Temple/1F/Entrance Vines Chest"},
	[BASE + 63] = {"@Forest Temple/1F/Gale Boomerang"},
	[BASE + 64] = {"@Forest Temple/1F/North Deku Like Chest"},
	[BASE + 65] = {"@Forest Temple/1F/Second Monkey Under Bridge Chest"},
	[BASE + 66] = {"@Forest Temple/1F/Totem Pole Chest"},
	[BASE + 67] = {"@Forest Temple/1F/West Deku Like Chest"},
	[BASE + 68] = {"@Forest Temple/1F/West Tile Worm Chest Behind Stairs"},
	[BASE + 69] = {"@Forest Temple/1F/West Tile Worm Room Vines Chest"},
	[BASE + 70] = {"@Forest Temple/1F/Windless Bridge Chest"},
	
	--Goron Mines Locations
	[BASE + 71] = {"@Goron Mines/2F/After Crystal Switch Room Magnet Wall Chest"},
	[BASE + 72] = {"@Goron Mines/2F/Beamos Room Chest"},
	[BASE + 73] = {"@Goron Mines/2F/Chest Before Dangoro"},
	[BASE + 74] = {"@Goron Mines/2F/Crystal Switch Room Small Chest"},
	[BASE + 75] = {"@Goron Mines/2F/Crystal Switch Room Underwater Chest"},
	[BASE + 76] = {"@Goron Mines/2F/Dangoro Chest"},
	[BASE + 77] = {"@Goron Mines/2F/Dungeon Reward"},
	[BASE + 78] = {"@Goron Mines/1F/Entrance Chest"},
	[BASE + 79] = {"@Goron Mines/2F/Fyrus Heart Container"},
	[BASE + 80] = {"@Goron Mines/1F/Gor Amato Chest"},
	[BASE + 81] = {"@Goron Mines/1F/Gor Amato Key Shard"},
	[BASE + 82] = {"@Goron Mines/1F/Gor Amato Small Chest"},
	[BASE + 83] = {"@Goron Mines/2F/Gor Ebizo Chest"},
	[BASE + 84] = {"@Goron Mines/2F/Gor Ebizo Key Shard"},
	[BASE + 85] = {"@Goron Mines/2F/Gor Liggs Chest"},
	[BASE + 86] = {"@Goron Mines/2F/Gor Liggs Key Shard"},
	[BASE + 87] = {"@Goron Mines/1F/Magnet Maze Chest"},
	[BASE + 88] = {"@Goron Mines/1F/Main Magnet Room Bottom Chest"},
	[BASE + 89] = {"@Goron Mines/2F/Main Magnet Room Top Chest"},
	[BASE + 90] = {"@Goron Mines/2F/Outside Beamos Chest"},
	[BASE + 91] = {"@Goron Mines/2F/Outside Clawshot Chest"},
	[BASE + 92] = {"@Goron Mines/2F/Outside Underwater Chest"},
	
	--Hyrule Castle Locations
	[BASE + 93] = {"@Hyrule Castle/2F/Big Key Chest"},
	[BASE + 94] = {"@Hyrule Castle/2F/East Wing Balcony Chest"},
	[BASE + 95] = {"@Hyrule Castle/1F/East Wing Boomerang Puzzle Chest"},
	[BASE + 96] = {"@Hyrule Castle/1F/Graveyard Switch Room/Back Left Chest"},
	[BASE + 97] = {"@Hyrule Castle/1F/Graveyard Switch Room/Front Left Chest"},
	[BASE + 98] = {"@Hyrule Castle/1F/Graveyard Switch Room/Right Chest"},
	[BASE + 99] = {"@Hyrule Castle/1F/Graveyard Owl Statue Chest"},
	[BASE + 100] = {"@Hyrule Castle/1F/King Bulblin Key"},
	[BASE + 101] = {"@Hyrule Castle/2F/Lantern Staircase Chest"},
	[BASE + 102] = {"@Hyrule Castle/2F/Main Hall Northeast Chest"},
	[BASE + 103] = {"@Hyrule Castle/2F/Main Hall Northwest Chest"},
	[BASE + 104] = {"@Hyrule Castle/2F/Main Hall Southwest Chest"},
	[BASE + 105] = {"@Hyrule Castle/Southeast Balcony Tower Chest"},
	[BASE + 106] = {"@Hyrule Castle/4F/Treasure Room/Eighth Small Chest"},
	[BASE + 107] = {"@Hyrule Castle/4F/Treasure Room/Fifth Chest"},
	[BASE + 108] = {"@Hyrule Castle/4F/Treasure Room/Fifth Small Chest"},
	[BASE + 109] = {"@Hyrule Castle/4F/Treasure Room/First Chest"},
	[BASE + 110] = {"@Hyrule Castle/4F/Treasure Room/First Small Chest"},
	[BASE + 111] = {"@Hyrule Castle/4F/Treasure Room/Fourth Chest"},
	[BASE + 112] = {"@Hyrule Castle/4F/Treasure Room/Fourth Small Chest"},
	[BASE + 113] = {"@Hyrule Castle/4F/Treasure Room/Second Chest"},
	[BASE + 114] = {"@Hyrule Castle/4F/Treasure Room/Second Small Chest"},
	[BASE + 115] = {"@Hyrule Castle/4F/Treasure Room/Seventh Small Chest"},
	[BASE + 116] = {"@Hyrule Castle/4F/Treasure Room/Sixth Small Chest"},
	[BASE + 117] = {"@Hyrule Castle/4F/Treasure Room/Third Chest"},
	[BASE + 118] = {"@Hyrule Castle/4F/Treasure Room/Third Small Chest"},
	[BASE + 119] = {"@Hyrule Castle/1F/West Courtyard Central Small Chest"},
	[BASE + 120] = {"@Hyrule Castle/1F/West Courtyard North Small Chest"},
	
	--Lakebed Temple Locations
	[BASE + 121] = {"@Lakebed Temple/1F/Before Deku Toad Alcove Chest"},
	[BASE + ] = {"@Lakebed Temple/"}
}