ScriptHost:AddWatchForCode("Split Map", "splitmap", splitmapchange)
ScriptHost:AddWatchForCode("Broadcast", "broadcast", broadcastchange)
ScriptHost:AddWatchForCode("HideLayout", "hidelayout", hidefrommainmap)

ScriptHost:AddWatchForCode("Bugs Amount", "bugsamount", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount0", "bug0", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount1", "bug1", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount2", "bug2", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount3", "bug3", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount4", "bug4", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount5", "bug5", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount6", "bug6", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount7", "bug7", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount8", "bug8", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount9", "bug9", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount10", "bug10", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount11", "bug11", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount12", "bug12", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount13", "bug13", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount14", "bug14", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount15", "bug15", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount16", "bug16", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount17", "bug17", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount18", "bug18", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount19", "bug19", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount20", "bug20", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount21", "bug21", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount22", "bug22", bugsamountchange)
ScriptHost:AddWatchForCode("Bugs Amount23", "bug23", bugsamountchange)
ScriptHost:AddOnLocationSectionChangedHandler("Bugs Amount Section", bugsamountchange)